"""
Django settings for booking_service project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path: Path) -> None:
    """Seed os.environ from a KEY=VALUE .env file, if present.

    Deliberately hand-rolled (Rule 5) instead of adding python-dotenv: it is ~10 lines, keeps
    the mechanism visible (there is no magic — .env just fills os.environ), and adds no
    dependency. Real environment variables win: we use setdefault(), so anything already
    exported in the shell is never overwritten by the file. Values are read verbatim — no
    quote-stripping — so don't wrap values in quotes in .env.
    """
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip())


# Load booking_service/.env (gitignored) before any setting reads os.environ.
_load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment; the insecure literal remains only as a dev fallback so the app
# still boots without a .env. Set DJANGO_SECRET_KEY to a real random value for anything real.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-ju=9+ua^ks1l(ep79&+i%-kye5vfc$sg1ntszcn2ni%h2i7v_i",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Env-driven so Docker can turn it off; defaults to True to preserve local `runserver` dev.
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

# Env-driven so the container can accept the host Caddy proxies under. Default covers local dev.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # Local apps
    'bookings',
]

MIDDLEWARE = [
    # Outermost, so it times the whole stack below it — the p99 the backpressure loop reads is the
    # full request, not just the view. It early-returns on /metrics so the scrape is not self-timed.
    'bookings.metrics.BookingMetricsMiddleware',
    # Must sit above CommonMiddleware / anything that can generate a response, so a CORS preflight
    # (OPTIONS) is answered before it. django-cors-headers is standard, async-safe plumbing here.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS: the vanilla frontend is served by the QUEUE service (:8001) and must be allowed to call
# THIS service's /book endpoint cross-origin. Dev only, that one origin (both host spellings). In
# production both services sit behind one origin (Caddy, Phase 12) and this can go away. No
# credentials — the admission pass is a Bearer header, not a cookie.
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8001",
    "http://localhost:8001",
]

ROOT_URLCONF = 'booking_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'booking_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "queuefair"),
        "USER": os.environ.get("DB_USER", "queuefair"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),  # no committed default; comes from .env
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", "5433"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- QueueFair: admission tokens --------------------------------------------------------------
# Shared HS256 secret used to VERIFY admission tokens minted by the queue service; it must match
# the queue service's signing secret. Required, with NO fallback default: a signing secret with a
# guessable default would let anyone forge admission tokens, so a missing value must crash the app
# loudly rather than silently accept forgeries.
ADMISSION_TOKEN_SECRET = os.environ["ADMISSION_TOKEN_SECRET"]
